### ISSUE TITLE
ERROR TypeError: Cannot read properties of undefined (reading 'coordinates')

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv#424]
triggered (in console) by: https://gcv.legumeinfo.org/gene;lis=glyma.Wm82.gnm4.ann1.Glyma.19G039050,glyma.Wm82.gnm4.ann1.Glyma.16G004800,glyma.Wm82.gnm4.ann1.Glyma.06G237366,glyma.Wm82.gnm4.ann1.Glyma.07G035600?q=glyma.Wm82.gnm4.ann1.Glyma.19G039050%20glyma.Wm82.gnm4.ann1.Glyma.16G004800%20glyma.Wm82.gnm4.ann1.Glyma.06G237366%20glyma.Wm82.gnm4.ann1.Glyma.07G035600&sources=lis&algorithm=repeat&match=10&mismatch=-1&gap=-1&score=30&threshold=25&bmatched=20&bintermediate=10&bmask=10&linkage=average&cthreshold=20&neighbors=10&matched=4&intermediate=5&bregexp=&border=chromosome&regexp=&order=distance

leaves client in awkward state:
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/2009605/170272026-ba730960-7f9e-4eab-b5df-4bed352d22e7.png">

**Comment by adf-ncgr** [comment]
this error seems to occur much more frequently than I'd care to admit. Here's a simpler example that seems to reproducibly trigger it: 
https://gcv.legumeinfo.org/gcv2/gene;lis=glyma.Wm82.gnm4.ann1.Glyma.18G052800

I'm not sure if this helps debug at all, but from what I've seen, the problem seems to have something to do with the region of the genome that the query gene resides in, since neighboring genes tend to yield the same issue.  For example:
https://gcv.legumeinfo.org/gcv2/gene;lis=glyma.Wm82.gnm4.ann1.Glyma.18G054600
manifests similarly, although now that I'm looking it actually reports a different error in the console:
main.fbb371a5cac15b03.js:1 ERROR RangeError: Invalid array length
    at l (806.d35139a33f71c5b1.js:1:217593)
    at 806.d35139a33f71c5b1.js:1:218100
    at Array.forEach (<anonymous>)
    at ew (806.d35139a33f71c5b1.js:1:217828)
    at $h (806.d35139a33f71c5b1.js:1:218136)
    at 806.d35139a33f71c5b1.js:1:219474
    at Array.forEach (<anonymous>)
    at Q0 (806.d35139a33f71c5b1.js:1:218998)
    at sw (806.d35139a33f71c5b1.js:1:221703)
    at 806.d35139a33f71c5b1.js:1:293420

**Comment by matthewwiese** [comment]
@adf-ncgr I've committed a fix for this in my dependency update/testing branch: [68ae01e](https://github.com/legumeinfo/gcv/commit/68ae01ef8530adf6e0a33acd9ac89d22630b54c6)

Ontologically it is related to #420 / #1023 where the alignment merge can't cleanly handle intervals:

* 420/1023 negative Array() length RangeErrors occurred due to overlapping intervals
* 424 undefined "coordinates" TypeError occurred due to unfillable gaps

Using the config from your second comment's example reproductions (thanks again for pointing out I could just pull this down, no idea why that didn't occur to me):

http://localhost:4200/gene;lis=glyma.Wm82.gnm4.ann1.Glyma.18G052800


<img width="1264" height="511" alt="Image" src="https://github.com/user-attachments/assets/6cad4d27-1b9f-467c-bdfd-402195a6fac9" />


http://localhost:4200/gene;lis=glyma.Wm82.gnm4.ann1.Glyma.18G054600


<img width="1258" height="542" alt="Image" src="https://github.com/user-attachments/assets/3b895078-0554-4f6f-bf76-33f2d0f32869" />


I'm pretty sure we can resolve this at cut time ([per Alan's TODO](https://github.com/legumeinfo/gcv/blob/main/src/assets/js/gcv/alignment/utils/merge-alignments.ts#L57)) and will keep working on it.

As an aside, I used Claude Opus 4.8 with ["medium" effort](https://platform.claude.com/docs/en/build-with-claude/effort) to help troubleshoot this. I could have tried DeepSeek (or GLM 5.2) but was more interested in solving/understanding the bug.
